"""Constants for the SL Metro Sign Home Assistant integration."""

from __future__ import annotations

DOMAIN = "sl_metro_sign_ha"
MQTT_DEPARTURES_TOPIC = "metro_sign/departures"
MQTT_DEVIATIONS_TOPIC = "metro_sign/deviations"
MQTT_STATE_TOPIC = "metro_sign/state"

CONF_MINIMUM_DISPLAY_BRIGHTNESS_PERCENT = "minimum_display_brightness_percent"
CONF_MAXIMUM_DISPLAY_BRIGHTNESS_PERCENT = "maximum_display_brightness_percent"

SETTINGS_SECTION_DEPARTURES = "departures"
SETTINGS_SECTION_DEVIATIONS = "deviations"
SETTINGS_SECTION_DISPLAY = "display"
SETTINGS_SECTION_SETTINGS_MENU = "settings_menu"

DEFAULT_FORECAST = 60
DEFAULT_MAX_SORTED_ENTRIES = 5
DEFAULT_MIN_PRIORITY_ENTRIES = 0
DEFAULT_ENABLE_DEVIATIONS = True
DEFAULT_MAX_DEVIATIONS = 5
DEFAULT_MIN_DEVIATION_IMPORTANCE = 1
DEFAULT_MIN_DISPLAY_BRIGHTNESS_PERCENT = 1
DEFAULT_MAX_DISPLAY_BRIGHTNESS_PERCENT = 100
MAX_STATION_ENTRIES = 5
MIN_SCAN_INTERVAL_SECONDS = 10
DEFAULT_SCAN_INTERVAL_SECONDS = 30
