"""Constants for the SL Metro Sign Home Assistant integration."""

from __future__ import annotations

DOMAIN = "sl_metro_sign_ha"
MQTT_DEPARTURES_TOPIC = "metro_sign/departures"
MQTT_DEVIATIONS_TOPIC = "metro_sign/deviations"
MQTT_STATE_TOPIC = "metro_sign/state"

SETTINGS_SECTION_API = "api"
SETTINGS_SECTION_DEPARTURES = "departures"
SETTINGS_SECTION_DEVIATIONS = "deviations"
SETTINGS_SECTION_SETTINGS_MENU = "settings_menu"

DEFAULT_FORECAST = 120
DEFAULT_MAX_SORTED_ENTRIES = 5
DEFAULT_ENABLE_PRIORITY = False
DEFAULT_MIN_PRIORITY_ENTRIES = 0
DEFAULT_ENABLE_DEVIATIONS = True
DEFAULT_MAX_DEVIATIONS = 5
DEFAULT_MIN_DEVIATION_IMPORTANCE = 1
MAX_STATION_ENTRIES = 5
MIN_SCAN_INTERVAL_SECONDS = 15
DEFAULT_SCAN_INTERVAL_SECONDS = 30
NU_THRESHOLD_SECONDS = 15
DEPARTURE_HHMM_THRESHOLD_MINUTES = 20